### ISSUE TITLE
Issues with RoomVisual

### ISSUE THREAD

**Issue by chobobobo** [screepers/Screeps-Typescript-Declarations#109]
RoomVisual constructor needs to have roomName as optional: http://docs.screeps.com/api/#RoomVisual

TextStyle needs 3 additional optional, I have extended it using:
interface TextStyle {
  font?: string | number;
  stroke?: string;
  strokeWidth?: number;
}
http://docs.screeps.com/api/#RoomVisual.text

**Comment by kotarou** [comment]
Will be fixed by PR #112

**Comment by anisoptera** [comment]
As @kotarou said, fixed by #112.
