### ISSUE TITLE
Take over of the repo and npm package

### ISSUE THREAD

**Issue by NhanHo** [screepers/Screeps-Typescript-Declarations#13]
I just had a move across the planet and didn't get your message until now. I will take over the repo and package if you don't want to maintain them anymore

**Comment by MarkoSulamagi** [comment]
I would appreciate it. I'm not playing anymore, but this package is used quite a lot. 120 downloads in the last week.

I need your username in https://www.npmjs.com/ to transfer the package.

**Comment by NhanHo** [comment]
My username on npm is also nhanho .

**Comment by MarkoSulamagi** [comment]
I'm unable to transfer the github repository, because you have a fork "NhanHo/Screeps-Typescript-Declarations already exists". Can you remove it so I can transfer the original?

**Comment by NhanHo** [comment]
Done

**Comment by MarkoSulamagi** [comment]
1) I transferred GitHUB repo. You have to accept.
2) I added you as collaborator in npmjs. There's no transfer functionality there. Just contributor.
3) What I usually do is that after every update I post it to the forum as well: http://support.screeps.com/hc/en-us/community/posts/207116485-Writing-Screep-bots-with-Typescript?page=1#
This helps new people see that the project is up to date and not obsolete. Helps grow the developer confidence in the library. 

I think that's all. If you're done then close this issue. If you need any help then let me know. You can see my email in my profile.
Thanks and good luck :)

**Comment by NhanHo** [comment]
Thank you :-).
