### ISSUE TITLE
Missing extrends

### ISSUE THREAD

**Issue by thorning** [screepers/Screeps-Typescript-Declarations#17]
It seems both `StructureContainer` and `Spawn` is missing the `extends Structure` in declaration.

I am very new to the game, so I might be overlooking something though. The error I'm getting is I cannot use them as `RoomObject` in i.e. `moveTo`

**Comment by NhanHo** [comment]
It's fixed in `a934d0a064f07014c5b0921fb80ac524025ce210`. Thanks for reporting!
