### ISSUE TITLE
lookFor(LOOK_TERRAIN) returns a string, not an array.

### ISSUE THREAD

**Issue by perennialinnocence** [screepers/Screeps-Typescript-Declarations#39]
I'm honestly not sure how this can be handled...

**Comment by valerian** [comment]
you're right and that's weird, since it returns an array for `Room.lookForAt(LOOK_TERRAIN, position)` and `RoomPosition.lookFor(LOOK_STRUCTURE)`, I think you should report it to Screeps instead

**Comment by valerian** [comment]
this has been fixed in Screeps now, so there is no more issue.
